### ISSUE TITLE
Update to the latest NestJS

### ISSUE THREAD

**Issue by lloiacono** [omermorad/nestjs-pact#8]
This package is requiring an old version of NestJs, at the time of writing NestJs `8.1.1` is available. Please update to the latest NestJs

**Comment by bewatts** [comment]
Any idea when we could get a bump to the newer versions of nest @omermorad? I'm trying to get Pact adopted at my company, and nestjs-pact not being supported on the new version is blocking me right now. 

I'd be happy to help on this; I'm a bit of a nestJS noob, so I'd probably need some guidance.

**Comment by omermorad** [comment]
@lloiacono sorry, missed that!
@bewatt

Sure do, I will release an update in the next few days!
BTW good to hear, Pact is truly amazing and a well-defined solution for integrations 😎

I will update here as soon as I finish ✌️

**Comment by omermorad** [comment]
Guys, @bewatts @lloiacono
Can you please try and install `nestjs-pact@2.1.0-alpha.1`? I think it will solve it

**Comment by omermorad** [comment]
@bewatts

**Comment by cristiangary-ml** [comment]
Thanks @omermorad ! I am in the same situation as @bewatts,  and the only missing part was Nestjs with Pact,  I re run our examples cases with the new version , and everything looks good.   Thanks !!!

**Comment by omermorad** [comment]
> Thanks @omermorad ! I am in the same situation as @bewatts, and the only missing part was Nestjs with Pact, I re run our examples cases with the new version , and everything looks good. Thanks !!!

Yay! Good to hear!! I'm going to release a stable version today, will update you as soon as it happens

**Comment by cristiangary-ml** [comment]
that's correct,     "nestjs-pact": "^2.1.0-alpha.1"

**Comment by omermorad** [comment]
> that's correct, "nestjs-pact": "^2.1.0-alpha.1"

Awesome!

**Comment by volodyad** [comment]
Hello @omermorad , should't you use version 3.0.0 ? 2.1.0 might brake all existing installation if users use ^2.x.x in case nestjs8 is not backward compatible with nestjs7

**Comment by omermorad** [comment]
It is backward compatible :)

**Comment by omermorad** [comment]
@volodyad @cristiangary-ml @bewatts @lloiacono 

version `2.1.0` has been released, please check :)

**Comment by bewatts** [comment]
Thanks for the quick work omermorad - I'm kind of slammed this week, I'll try and confirm for you as quickly as I can.  Thus far, I can confirm that the installation has worked.
